### ISSUE TITLE
PRODUCT_NAME was misdefined

### ISSUE THREAD

**Issue by GRyabkin** [bielikb/fastlane-plugin-create_xcframework#4]
fastlane finished with errors

[!] ▸ PRODUCT_NAME was misdefined: `MySDK`. Please, provide :product_name option

**Comment by alteral** [comment]
Looks like you've provided an incorrect `PRODUCT_NAME`.

Try to remove `product_name` option from your `create_xcframework` lane, will it help?

**Comment by bielikb** [comment]
This question was resolved by the author by changing his project setup. Im closing this issue.

**Comment by mbt-laurent-n** [comment]
I had this issue (I'm on macOS 11.4 with Xcode 12.5). However it seems that it comes from this line:
https://github.com/bielikb/fastlane-plugin-create_xcframework/blob/328af1ca322ab81db2273954aef94b1efbefd4f7/lib/fastlane/plugin/create_xcframework/helper/create_xcframework_helper.rb#L29

it gives a wrong path instead of mine:
` framework_path = "#{xcarchive_path_for_destination(framework_index)}/Products/Frameworks/#{framework}" `
